
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfsmqxbywaxcxqnpgton.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmc21xeGJ5d2F4Y3hxbnBndG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzQxNDUsImV4cCI6MjA1OTQ1MDE0NX0.pFoQLTGJPTrGtVOSK_4fkouBE5w74KU-HDEemMY9e-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
